# require_all 'app'
#
# Should these have more info than name, how are they connected to Show?
# How do you connect episode instances and user instances through View? Should watch_episode method take in an episode instance?






binding.pry

# Season 1
# Episode.create(name: "Welcome to the Hellmouth")
# Episode.create(name: "The Harvest")
# Episode.create(name: "Witch")
# Episode.create(name: "Teacher's Pet")
# Episode.create(name: "Never Kill a Boy on the First Date")
# Episode.create(name: "The Pack")
# Episode.create(name: "Angel")
# Episode.create(name: "I, Robot... You, Jane")
# Episode.create(name: "The Puppet Show")
# Episode.create(name: "Nightmares")
# Episode.create(name: "Out of Mind, Out of Sight")
# Episode.create(name: "Prophecy Girl")
#
#
# Season 2
# Episode.create(name: "When She Was Bad")
# Episode.create(name: "Some Assembly Required")
# Episode.create(name: "School Hard")
# Episode.create(name: "Inca Mummy Girl")
# Episode.create(name: "Reptile Boy")
# Episode.create(name: "Halloween")
# Episode.create(name: "Lie to Me")
# Episode.create(name: "The Dark Age")
# Episode.create(name: "What's My Line (Part 1)")
# Episode.create(name: "What's My Line (Part 2)")
# Episode.create(name: "Ted")
# Episode.create(name: "Bad Eggs")
# Episode.create(name: "Surprise")
# Episode.create(name: "Innocence")
# Episode.create(name: "Phases")
# Episode.create(name: "Bewitched, Bothered and Bewildered")
# Episode.create(name: "Passion")
# Episode.create(name: "Killed By Death")
# Episode.create(name: "I Only Have Eyes for You")
# Episode.create(name: "Go Fish")
# Episode.create(name: "Becoming (Part 1)")
# Episode.create(name: "Becoming (Part 2)")
#
#
# Season 3
# Episode.create(name: "Anne")
# Episode.create(name: "Dead Man's Party")
# Episode.create(name: "Faith, Hope & Trick")
# Episode.create(name: "Beauty and the Beasts")
# Episode.create(name: "Homecoming")
# Episode.create(name: "Band Candy")
# Episode.create(name: "Revelations")
# Episode.create(name: "Lovers Walk")
# Episode.create(name: "The Wish")
# Episode.create(name: "Amends")
# Episode.create(name: "Gingerbread")
# Episode.create(name: "Helpless")
# Episode.create(name: "The Zeppo")
# Episode.create(name: "Bad Girls")
# Episode.create(name: "Consequences")
# Episode.create(name: "Doppelgangland")
# Episode.create(name: "Enemies")
# Episode.create(name: "Earshot")
# Episode.create(name: "Choices")
# Episode.create(name: "The Prom")
# Episode.create(name: "Graduation Day")
#
#
# Season 4
# Episode.create(name: "The Freshman")
# Episode.create(name: "Living Conditions")
# Episode.create(name: "The Harsh Light of Day")
# Episode.create(name: "Fear, Itself")
# Episode.create(name: "Beer Bad")
# Episode.create(name: "Wild at Heart")
# Episode.create(name: "The Initiative")
# Episode.create(name: "Pangs")
# Episode.create(name: "Something Blue")
# Episode.create(name: "Hush")
# Episode.create(name: "Doomed")
# Episode.create(name: "A New Man")
# Episode.create(name: "The I in Team")
# Episode.create(name: "Goodbye Iowa")
# Episode.create(name: "This Year's Girl (Part 1)")
# Episode.create(name: "Who Are You? (Part 2)")
# Episode.create(name: "Superstar")
# Episode.create(name: "Where the Wild Things Are")
# Episode.create(name: "New Moon Rising")
# Episode.create(name: "The Yoko Factor (Part 1)")
# Episode.create(name: "Primeval (Part 2)")
# Episode.create(name: "Restless")
#
#
# Season 5
# Episode.create(name: "Buffy vs. Dracula")
# Episode.create(name: "Real Me")
# Episode.create(name: "The Replacement")
# Episode.create(name: "Out of My Mind")
# Episode.create(name: "No Place Like Home")
# Episode.create(name: "Family")
# Episode.create(name: "Fool For Love")
# Episode.create(name: "Shadow")
# Episode.create(name: "Listening to Fear")
# Episode.create(name: "Into the Woods")
# Episode.create(name: "Triangle")
# Episode.create(name: "Checkpoint")
# Episode.create(name: "Blood Ties")
# Episode.create(name: "Crush")
# Episode.create(name: "I Was Made to Love You")
# Episode.create(name: "The Body")
# Episode.create(name: "Forever")
# Episode.create(name: "Intervention")
# Episode.create(name: "Tough Loves")
# Episode.create(name: "Spiral")
# Episode.create(name: "The Weight of the World")
# Episode.create(name: "The Gift")
#
#
# Season 6
# Episode.create(name: "Bargaining (Part 1)")
# Episode.create(name: "Bargaining (Part 2)")
# Episode.create(name: "After Life")
# Episode.create(name: "Flooded")
# Episode.create(name: "Life Serial")
# Episode.create(name: "All the Way")
# Episode.create(name: "Once More, With Feeling")
# Episode.create(name: "Tabula Rasa")
# Episode.create(name: "Smashed")
# Episode.create(name: "Wrecked")
# Episode.create(name: "Gone")
# Episode.create(name: "Doublemeat Palace")
# Episode.create(name: "Dead Things")
# Episode.create(name: "Older and Far Away")
# Episode.create(name: "As You Were")
# Episode.create(name: "Hell's Bells")
# Episode.create(name: "Normal Again")
# Episode.create(name: "Entropy")
# Episode.create(name: "Seeing Red")
# Episode.create(name: "Villains")
# Episode.create(name: "Two to Go")
# Episode.create(name: "Grave")
#
#
#
# Season 7
# Episode.create(name: "Lessons")
# Episode.create(name: "Beneath You")
# Episode.create(name: "Same Time, Same Place")
# Episode.create(name: "Help")
# Episode.create(name: "Selfless")
# Episode.create(name: "Him")
# Episode.create(name: "Conversations with Dead People")
# Episode.create(name: "Sleeper")
# Episode.create(name: "Never Leave Me")
# Episode.create(name: "Bring On the Night")
# Episode.create(name: "Showtime")
# Episode.create(name: "Potential")
# Episode.create(name: "Get It Done")
# Episode.create(name: "Storyteller")
# Episode.create(name: "Lies My Parents Told Me")
# Episode.create(name: "Dirty Girls")
# Episode.create(name: "Empty Places")
# Episode.create(name: "Touched")
# Episode.create(name: "End of Days")
# Episode.create(name: "Chosen")
