# require_all 'app'
#
# Should these have more info than name, how are they connected to Show?
# How do you connect episode instances and user instances through View? Should watch_episode method take in an episode instance?






binding.pry

# Season 1
# Episode.create(name: "Welcome to the Hellmouth", season: "Season 1")
# Episode.create(name: "The Harvest", season: "Season 1")
# Episode.create(name: "Witch", season: "Season 1")
# Episode.create(name: "Teacher's Pet", season: "Season 1")
# Episode.create(name: "Never Kill a Boy on the First Date", season: "Season 1")
# Episode.create(name: "The Pack", season: "Season 1")
# Episode.create(name: "Angel", season: "Season 1")
# Episode.create(name: "I, Robot... You, Jane", season: "Season 1")
# Episode.create(name: "The Puppet Show", season: "Season 1")
# Episode.create(name: "Nightmares", season: "Season 1")
# Episode.create(name: "Out of Mind, Out of Sight", season: "Season 1")
# Episode.create(name: "Prophecy Girl", season: "Season 1")
#
#
# Season 2
# Episode.create(name: "When She Was Bad", season: "Season 2")
# Episode.create(name: "Some Assembly Required", season: "Season 1")
# Episode.create(name: "School Hard", season: "Season 2")
# Episode.create(name: "Inca Mummy Girl", season: "Season 2")
# Episode.create(name: "Reptile Boy", season: "Season 2")
# Episode.create(name: "Halloween", season: "Season 2")
# Episode.create(name: "Lie to Me", season: "Season 2")
# Episode.create(name: "The Dark Age", season: "Season 2")
# Episode.create(name: "What's My Line (Part 1)", season: "Season 2")
# Episode.create(name: "What's My Line (Part 2)", season: "Season 2")
# Episode.create(name: "Ted", season: "Season 2")
# Episode.create(name: "Bad Eggs", season: "Season 2")
# Episode.create(name: "Surprise", season: "Season 2")
# Episode.create(name: "Innocence", season: "Season 2")
# Episode.create(name: "Phases", season: "Season 2")
# Episode.create(name: "Bewitched, Bothered and Bewildered", season: "Season 2")
# Episode.create(name: "Passion", season: "Season 2")
# Episode.create(name: "Killed By Death", season: "Season 2")
# Episode.create(name: "I Only Have Eyes for You", season: "Season 2")
# Episode.create(name: "Go Fish", season: "Season 2")
# Episode.create(name: "Becoming (Part 1)", season: "Season 2")
# Episode.create(name: "Becoming (Part 2)", season: "Season 2")
#
#
# Season 3
# Episode.create(name: "Anne", season: "Season 3")
# Episode.create(name: "Dead Man's Party", season: "Season 3")
# Episode.create(name: "Faith, Hope & Trick", season: "Season 3")
# Episode.create(name: "Beauty and the Beasts", season: "Season 3")
# Episode.create(name: "Homecoming", season: "Season 3")
# Episode.create(name: "Band Candy", season: "Season 3")
# Episode.create(name: "Revelations", season: "Season 3")
# Episode.create(name: "Lovers Walk", season: "Season 3")
# Episode.create(name: "The Wish", season: "Season 3")
# Episode.create(name: "Amends", season: "Season 3")
# Episode.create(name: "Gingerbread", season: "Season 3")
# Episode.create(name: "Helpless", season: "Season 3")
# Episode.create(name: "The Zeppo", season: "Season 3")
# Episode.create(name: "Bad Girls", season: "Season 3")
# Episode.create(name: "Consequences", season: "Season 3")
# Episode.create(name: "Doppelgangland", season: "Season 3")
# Episode.create(name: "Enemies", season: "Season 3")
# Episode.create(name: "Earshot", season: "Season 3")
# Episode.create(name: "Choices", season: "Season 3")
# Episode.create(name: "The Prom", season: "Season 3")
# Episode.create(name: "Graduation Day", season: "Season 3")
#
#
# Season 4
# Episode.create(name: "The Freshman", season: "Season 4")
# Episode.create(name: "Living Conditions", season: "Season 4")
# Episode.create(name: "The Harsh Light of Day", season: "Season 4")
# Episode.create(name: "Fear, Itself", season: "Season 4")
# Episode.create(name: "Beer Bad", season: "Season 4")
# Episode.create(name: "Wild at Heart", season: "Season 4")
# Episode.create(name: "The Initiative", season: "Season 4")
# Episode.create(name: "Pangs", season: "Season 4")
# Episode.create(name: "Something Blue", season: "Season 4")
# Episode.create(name: "Hush", season: "Season 4")
# Episode.create(name: "Doomed", season: "Season 4")
# Episode.create(name: "A New Man", season: "Season 4")
# Episode.create(name: "The I in Team", season: "Season 4")
# Episode.create(name: "Goodbye Iowa", season: "Season 4")
# Episode.create(name: "This Year's Girl (Part 1)", season: "Season 4")
# Episode.create(name: "Who Are You? (Part 2)", season: "Season 4")
# Episode.create(name: "Superstar", season: "Season 4")
# Episode.create(name: "Where the Wild Things Are", season: "Season 4")
# Episode.create(name: "New Moon Rising", season: "Season 4")
# Episode.create(name: "The Yoko Factor (Part 1)", season: "Season 4")
# Episode.create(name: "Primeval (Part 2)", season: "Season 4")
# Episode.create(name: "Restless", season: "Season 4")
#
#
# Season 5
# Episode.create(name: "Buffy vs. Dracula", season: "Season 5")
# Episode.create(name: "Real Me", season: "Season 5")
# Episode.create(name: "The Replacement", season: "Season 5")
# Episode.create(name: "Out of My Mind", season: "Season 5")
# Episode.create(name: "No Place Like Home", season: "Season 5")
# Episode.create(name: "Family", season: "Season 5")
# Episode.create(name: "Fool For Love", season: "Season 5")
# Episode.create(name: "Shadow", season: "Season 5")
# Episode.create(name: "Listening to Fear", season: "Season 5")
# Episode.create(name: "Into the Woods", season: "Season 5")
# Episode.create(name: "Triangle", season: "Season 5")
# Episode.create(name: "Checkpoint", season: "Season 5")
# Episode.create(name: "Blood Ties", season: "Season 5")
# Episode.create(name: "Crush", season: "Season 5")
# Episode.create(name: "I Was Made to Love You", season: "Season 5")
# Episode.create(name: "The Body", season: "Season 5")
# Episode.create(name: "Forever", season: "Season 5")
# Episode.create(name: "Intervention", season: "Season 5")
# Episode.create(name: "Tough Loves", season: "Season 5")
# Episode.create(name: "Spiral", season: "Season 5")
# Episode.create(name: "The Weight of the World", season: "Season 5")
# Episode.create(name: "The Gift", season: "Season 5")
#
#
# Season 6
# Episode.create(name: "Bargaining (Part 1)", season: "Season 6")
# Episode.create(name: "Bargaining (Part 2)", season: "Season 6")
# Episode.create(name: "After Life", season: "Season 6")
# Episode.create(name: "Flooded", season: "Season 6")
# Episode.create(name: "Life Serial", season: "Season 6")
# Episode.create(name: "All the Way", season: "Season 6")
# Episode.create(name: "Once More, With Feeling", season: "Season 6")
# Episode.create(name: "Tabula Rasa", season: "Season 6")
# Episode.create(name: "Smashed", season: "Season 6")
# Episode.create(name: "Wrecked", season: "Season 6")
# Episode.create(name: "Gone", season: "Season 6")
# Episode.create(name: "Doublemeat Palace", season: "Season 6")
# Episode.create(name: "Dead Things", season: "Season 6")
# Episode.create(name: "Older and Far Away", season: "Season 6")
# Episode.create(name: "As You Were", season: "Season 6")
# Episode.create(name: "Hell's Bells", season: "Season 6")
# Episode.create(name: "Normal Again", season: "Season 6")
# Episode.create(name: "Entropy", season: "Season 6")
# Episode.create(name: "Seeing Red", season: "Season 6")
# Episode.create(name: "Villains", season: "Season 6")
# Episode.create(name: "Two to Go", season: "Season 6")
# Episode.create(name: "Grave", season: "Season 6")
#
#
#
# Season 7
# Episode.create(name: "Lessons", season: "Season 7")
# Episode.create(name: "Beneath You", season: "Season 7")
# Episode.create(name: "Same Time, Same Place", season: "Season 7")
# Episode.create(name: "Help", season: "Season 7")
# Episode.create(name: "Selfless", season: "Season 7")
# Episode.create(name: "Him", season: "Season 7")
# Episode.create(name: "Conversations with Dead People", season: "Season 7")
# Episode.create(name: "Sleeper", season: "Season 7")
# Episode.create(name: "Never Leave Me", season: "Season 7")
# Episode.create(name: "Bring On the Night", season: "Season 7")
# Episode.create(name: "Showtime", season: "Season 7")
# Episode.create(name: "Potential", season: "Season 7")
# Episode.create(name: "Get It Done", season: "Season 7")
# Episode.create(name: "Storyteller", season: "Season 7")
# Episode.create(name: "Lies My Parents Told Me", season: "Season 7")
# Episode.create(name: "Dirty Girls", season: "Season 7")
# Episode.create(name: "Empty Places", season: "Season 7")
# Episode.create(name: "Touched", season: "Season 7")
# Episode.create(name: "End of Days", season: "Season 7")
# Episode.create(name: "Chosen", season: "Season 7")
